### PR TITLE
support for string_hex

### PR DESCRIPTION
**Pull request by anthonysomerset**
this relates to https://github.com/puppetlabs/puppetlabs-firewall/pull/800 support for hex-string matching options

### CODE REVIEW

**Comment by alexharv074** [comment]
@anthonysomerset Looks like more work needed on this and happy to help. Just to clarify though, are you saying that you need this module's Array functionality made available for the string_hex parameter? Second question, is that feature actually in a released version of the firewall module? My release process here is to wait for firewall module releases, and then patch this module to match it. Due to the design of this module, I can't really support a forthcoming feature.

**Comment by anthonysomerset** [comment]
no not yet released correct

yes i wanted both string_hex for the firewall module (DNS tunnelling blocking of specific domains) and then in an array format to keep my manifests slightly more manageable. it works well enough in this iteration though :)

**Comment by anthonysomerset** [comment]
Hi, 2 examples of usage

case 1: string_hex not in array but supporting for other existing params:
```
  firewall_multi { '102 DENY NULL QUERIES':
    dport  => 53,
    proto  => ['tcp', 'udp'],
    string_hex => '|00000a0001|',
    string_algo => 'bm',
    string_from => 38,
    state => 'NEW',
    action => 'drop',
    provider => ['iptables','ip6tables'],    
  }
```
This particularly rule generates 2 rules in both ipv4 and ipv6 iptables for TCP and UDP like any other rule right now

generates the following rules for IPtables (output from iptables-save):

```
-A INPUT -p tcp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|00000a0001|" --algo bm --from 38 --to 65535 -m comment --comment "102 DENY NULL QUERIES protocol tcp using provider iptables" -j DROP
-A INPUT -p udp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|00000a0001|" --algo bm --from 38 --to 65535 -m comment --comment "102 DENY NULL QUERIES protocol udp using provider iptables" -j DROP
```

Case 2 an array/hash for string_hex:

```
  firewall_multi { '102 DENY BAD DOMAINS QUERIES':
    dport  => 53,
    proto  => ['tcp', 'udp'],
    string_hex => [
    '|03317966026465|',
    '|03353372026465|',
    '|03387536026465|',
    ],
    string_algo => 'bm',
    string_from => 30,
    state => 'NEW',
    action => 'drop',
    provider => ['iptables','ip6tables'],    
  }
```

this is a shortened version of my actual rule that does the same but also iterates based on the string_hex patterns listed

generates the following iptables rules

```
-A INPUT -p tcp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|0330367802696e|" --algo bm --from 30 --to 65535 -m comment --comment "102 DENY BAD DOMAINS QUERIES protocol tcp using provider iptables hex string block |0330367802696e|" -j DROP
-A INPUT -p tcp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|0330396a02696e|" --algo bm --from 30 --to 65535 -m comment --comment "102 DENY BAD DOMAINS QUERIES protocol tcp using provider iptables hex string block |0330396a02696e|" -j DROP
-A INPUT -p tcp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|0330396d02696e|" --algo bm --from 30 --to 65535 -m comment --comment "102 DENY BAD DOMAINS QUERIES protocol tcp using provider iptables hex string block |0330396d02696e|" -j DROP
-A INPUT -p tcp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|0330783702696e|" --algo bm --from 30 --to 65535 -m comment --comment "102 DENY BAD DOMAINS QUERIES protocol tcp using provider iptables hex string block |0330783702696e|" -j DROP
-A INPUT -p udp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|037a763302696e|" --algo bm --from 30 --to 65535 -m comment --comment "102 DENY BAD DOMAINS QUERIES protocol udp using provider iptables hex string block |037a763302696e|" -j DROP
-A INPUT -p udp -m multiport --dports 53 -m state --state NEW -m string --hex-string "|037a7a3302696e|" --algo bm --from 30 --to 65535 -m comment --comment "102 DENY BAD DOMAINS QUERIES protocol udp using provider iptables hex string block |037a7a3302696e|" -j DROP
```

**Comment by alexharv074** [comment]
Awesome. Shall I use your branch as the starting point and implement? I'll leave the feature on a branch until upstream releases the feature in puppetlabs/firewall, if you're ok with all that.

**Comment by alexharv074** [comment]
@anthonysomerset , I have moved your branch from your fork to this repo, I rewrote the history a little because I'm like that, I added a passing unit test and updated the docs. I also added you as a collaborator on the project. 

You can use the feature in the mean time by pointing your Puppetfile to this branch.

Meanwhile, just ping me when your PR gets released in an actual release of the firewall module and then I'll merge that branch and release again here.

I'm closing this PR in favour of the new branch here https://github.com/alexharv074/puppet-firewall_multi/pull/17

**Pull request closed without merging**
