### PR TITLE
remove onduplicatebehaviour option

### PR DESCRIPTION
**Pull request by robertc99**
onduplicatebehaviour has been removed from firewall module. This matches the change.

### CODE REVIEW

**Comment by robertc99** [comment]
Thats fine. Im using my fork for the moment. Im using the main branch of firewall for the stdlib9 support.

I just wanted to make sure you'd be ready to release when firewall next releases. Although, they dont seem to be in any hurry.


But given that the change is sitting in firewall HEAD, I would have thought it made sense for the change to be in your HEAD ready to release.

You might want to update metadata.json as well.

**Comment by robertc99** [comment]
firewall 6 has been released...

**Comment by alexharv074** [comment]
Thanks @robertc99  I will get this sorted out this evening local time.

**Comment by robertc99** [comment]
they should really integrate this into the firewall module. Have talked to the firewall maintainers?

**Comment by alexharv074** [comment]
@robertc99 Yes I agree, I'm probably too busy to lead any discussions on that, but if they'd like to look at doing that, I'd be more than happy for it.

**Comment by alexharv074** [comment]
@robertc99 released. Let me know if you have any issues consuming v6.0.0 of this? The Forge all changed and I may not have got my head around it all!

**Comment by robertc99** [comment]
yeah, that seems to work ok. Thanks.
Now I just have to wait for a bunch of other modules to update..

It doesnt work against firewall 5 any more for some reason.
But thats fine.

And your metadata.json doesnt mention RHEL 8 or 9 or Rocky or Alma Linux.
You might want to align it with the metadata from firewall.
But Im not sure what if anything actually uses the metadata.json.

**Comment by alexharv074** [comment]
@robertc99 I think metadata.json is just me telling people what I tested it on and the truth is I haven't tested it on anything although from experience there have never been issues in the past!

**Comment by alexharv074** [comment]
(And no, none of these 'firewall multi' releases are expected to work against any other version of firewall than the one whose version matches. Long story!)

**Pull request merged**
